[package]
name = "redactor"
version = "0.1.0-pre6"
authors = ["Joe Corcoran <joe@corcoran.io>"]

[dependencies]
base64 = "0.5"
exec = "0.2"
getopts = "0.2"
pty = "0.2"
tempdir = "0.3"

[profile.release]
lto = true
